### ISSUE TITLE
Set Only 1 Swipe Action open in 1 time

### ISSUE THREAD

**Issue by WenLonG12345** [st235/SwipeToActionLayout#2]
Hi, thanks for this awesome library and it is very useful for me! :)

By the way, can you help to add a feature to set only allow 1 swipe action open in 1 time? 
For example, if another swipe action is triggered, all the others swipe action will be closed. 

Thanks again for this library and hope to see this feature soon 👍🏻

**Comment by st235** [comment]
Hello @WenLonG12345 👋

I am so sorry for the delay, I've missed the notification. I do not know why I have not noticed it earlier.
First of all, thank you for using this library and I am glad to hear that you found it useful!

You can find an example at the sample app: https://github.com/st235/SwipeToActionLayout/blob/master/app/src/main/java/github/com/st235/swipetoactionlayout/ShowcaseActivity.kt#L67

If the action has been detected you can just close the menu. Is that what you meant?

Best regards,
Alex
