### ISSUE TITLE
How to enable or disable actions

### ISSUE THREAD

**Issue by nayanasrirama** [st235/SwipeToActionLayout#4]
Hi, thank you for creating this library. It is really useful in my current working project.

I have a question regarding swipe actions if we can enable or disable actions based on a condition. Suppose I have a scenario where I have got add, remove & edit actions, any of three can be enabled or disabled (icon shouldn't appear ). And when i swipe any record only those icons should be visible which are enabled. 

Please let me know your inputs @st235

**Comment by st235** [comment]
Hello @nayanasrirama 👋

Thank you very much for using the library! I want to let you know that I saw your question and will return to you as soon as possible.

**Comment by st235** [comment]
Hello @nayanasrirama 👋

Thank you for your patience. Unfortunately, this feature is not supported officially. 

However, I can offer you two ways to resolve the issue:
1. You can completely reload your actions list when the list has changed using [this property](https://github.com/st235/SwipeToActionLayout/blob/master/lib-swipetoactionlayout/src/main/java/github/com/st235/lib_swipetoactionlayout/SwipeToActionLayout.kt#L66)
2. As the layout itself is a custom `view group` you can find your action by [actionId](https://github.com/st235/SwipeToActionLayout/blob/master/lib-swipetoactionlayout/src/main/java/github/com/st235/lib_swipetoactionlayout/ActionFactory.kt#L38) using `findViewById` and then disable the view (`isEnabled = false`). It will be on the list although it won't be interactive at all.

Let me know if this information was helpful.

**Comment by nayanasrirama** [comment]
Hi @st235 , 

Thank you for your answer. I've solved it myself, in my case I want the icons to be hidden based on specific condition. Since the swipe actions are always fixed and I know the order of the actions too then I can pass the index of the menu item (swipe action) to set the visibility. 

// passing the index to hide the icon, isActionEnabled is a boolean value.

`if(isActionEnabled)`
`{`
   `swipeToActionLayout[1].visibility = View.GONE`
 `}`

Here swipeToActionLayout is the id of my SwipeToActionLayout (parent layout).

**Comment by st235** [comment]
Oh, cool!
Glad to hear that you were able to resolve the issue.

Thank you very much for the feedback!
