### ISSUE TITLE
How to close other SwipeToActionLayout in recyclerView

### ISSUE THREAD

**Issue by mrkayza** [st235/SwipeToActionLayout#5]
Hi.
Thanks for great lib.
I'm using SwipeToActionLayout for RecyclerView.Adapter.
When SwipeToActionLayout opened, i want close other SwipeToActionLayout is opening.
How do it ?
Thanks

**Comment by st235** [comment]
Hello @mrkayza 👋

Thank you very much for using the library and sorry for delay - somehow I missed the issue. 

You can use [ActionBindHelper](https://github.com/st235/SwipeToActionLayout/blob/master/lib-swipetoactionlayout/src/main/java/github/com/st235/lib_swipetoactionlayout/ActionBindHelper.kt). You can find example [here](https://github.com/st235/SwipeToActionLayout/blob/master/app/src/main/java/github/com/st235/swipetoactionlayout/ContactsAdapter.kt#L22).

**Comment by st235** [comment]
@mrkayza I am just wondering if the solution worked for you?

**Comment by st235** [comment]
I am closing the issue as there is no any activity. 
Hopefully, the proposed solution has helped you 🤞
