### ISSUE TITLE
The onClosed callback is triggered by the first swipe

### ISSUE THREAD

**Issue by linxiangcheer** [st235/SwipeToActionLayout#7]
There's something wrong here。-。-

**Comment by st235** [comment]
hello @linxiangcheer 👋

First of all, thank you so much for using the library. Can you, please, elaborate on your inquiry: the library version, what you did (steps to represent), what you see vs. what is expected? I will really appreciate any additional information about the issue.

Best regards,
Alex

**Comment by st235** [comment]
@linxiangcheer I checked your issue and can confirm that the issue exists.
I've created a pull request with fix and will update when the new version will be ready

**Comment by st235** [comment]
@linxiangcheer `1.1.0` version is live now in maven.
Thank you very much for highlighting the issue to me!
